In [1]:
# Numpy: import numpy liabrary
import numpy as np


In [2]:
# array: 
# one dimensional
a=np.array([1,2,3,4,5,6])
# two dimensional
b=np.array([[1,2,3],[4,5,6]])
print(" one dimensional array :")
print(a)
print(" two dimensional array :")
print(b)

 one dimensional array :
[1 2 3 4 5 6]
 two dimensional array :
[[1 2 3]
 [4 5 6]]


In [3]:
# format: the standard binary format
# shape
c=np.array([[1,2,3],[4,5,6]])
print("shape of c {}".format(c.shape))

shape of c (2, 3)


In [4]:
# ndim : represents the number of dimensions of the ndarray
d=np.array([[1,2,3],[4,5,6]])
print("ndim {}".format(d.ndim))

ndim 2


In [5]:
# size : calculate the total elements or values  in the array
e=np.array([[1,2,3],[4,5,6]])
print("size {}".format(e.size))

size 6


In [6]:
# dtype : describes the bytes in the fixed-size block of memory
f=np.array([[1,2,3],[4,5,6]])
print("dtype {}".format(f.dtype))

dtype int64


In [7]:
# itemsize: returns the size of each element of  NumPy array
g=np.array([[1,2,3],[4,5,6]])
print("itemsize {}".format(g.itemsize))

itemsize 8


In [8]:
# data:
h=np.array([[1,2,3],[4,5,6]])
print("data {}".format(h.data))

data <memory at 0x7fa1012bce10>


In [9]:
# sum: returns the sum of array elements over the specified axis
i=np.array([[1,2,3],[4,5,6]])
print(i.sum())

21


In [10]:
# multiplication: multiplication of two array
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
mul=np.dot(A,B)
print("multiplication :")
print(mul)

multiplication :
[[16 19]
 [26 31]]


In [11]:
# addition: performs element wise addition on NumPy arrays
j = [[1, 2], [2, 3]]
k = [[4, 5], [6, 7]]
ad=np.add(j,k)
print("addition :")
print(ad)

addition :
[[ 5  7]
 [ 8 10]]


In [13]:
#reshape: changing the shape of an array
l=np.array([1,2,3,4,5,6])
re=l.reshape(2,3)
print(re)

[[1 2 3]
 [4 5 6]]


In [14]:
# maximum: find the element-wise maximum of array elements
a=np.array([1,2,3,4,5,6])
print("maximum is ",a.max())

maximum is  6


In [15]:
# minimum : find the element-wise minimum of array elements
a=np.array([1,2,3,4,5,6])
print("minimum is ",a.min())

minimum is  1


In [16]:
# minimum along the axis
re=np.array([[1,2,3],[4,5,6]])
print("minimum is ",re.min(axis=0))

minimum is  [1 2 3]


In [17]:
#square root: calculate the positive square root of a number or the elements of an array
re=np.array([[1,4,9],[16,25,36]])
print(np.sqrt(re))

[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
# standard deviation : calculates the standard deviation of given data along a specified axis
re=np.array([[1,4,9],[16,25,36]])
print("standard deviation ",np.std(re))

standard deviation  12.212243401148248


In [20]:
# merging : merge two arrays
# vstack : Stack arrays in sequence vertically 

a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
v=np.vstack((a,b))
print("vertical :")
print(v)

vertical :
[[1 2]
 [4 5]
 [8 7]
 [5 4]]


In [21]:
# horizontal : combines a sequence of arrays along their horizontal axis
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
print("horizontal :")
print(h)

horizontal :
[[1 2 8 7]
 [4 5 5 4]]


In [22]:
# arange : produces an array of sequential numbers within a given interval
a=np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
a=np.arange(0,23,5,float)
print("data type: ",a.dtype)

data type:  float64


In [26]:
# linspace: allows you to create evenly spaced arrays with a specified number of elements
a=np.linspace(0,22,15)
print(a)
print("data type: ",a.dtype)

[ 0.          1.57142857  3.14285714  4.71428571  6.28571429  7.85714286
  9.42857143 11.         12.57142857 14.14285714 15.71428571 17.28571429
 18.85714286 20.42857143 22.        ]
data type:  float64


In [27]:
#transpose: moving the rows data to the column and columns data to the rows
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
ht=h.T
print(ht)

[[1 4]
 [2 5]
 [8 5]
 [7 4]]


In [28]:
# nditer :-provides many flexible ways to visit all the elements of one or more arrays in a systematic fashion
for i in np.nditer(ht):
    print("element :",i)

element : 1
element : 2
element : 8
element : 7
element : 4
element : 5
element : 5
element : 4


In [29]:
# hsplit: split an array into multiple sub-arrays horizontally (column-wise)
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
h1=np.hsplit(h,2)
print(h1)

[array([[1, 2],
       [4, 5]]), array([[8, 7],
       [5, 4]])]


In [30]:
#vsplit: split an array into multiple sub-arrays vertically (row-wise)
a=np.array([[1,2],[4,5]])
b=np.array([[8,7],[5,4]])
h=np.hstack((a,b))
h1=np.vsplit(h,2)
print(h1)

[array([[1, 2, 8, 7]]), array([[4, 5, 5, 4]])]
